Running with gitlab-runner 16.11.2 (1d04b67a)
  on l7lp2apmglr0003-Prod-Global-GitLab-Cloud-Shell-apihub-shared ZNFLWGL4, system ID: s_842e1c8182d6
Resolving secrets
Preparing the "shell" executor
00:00
Using Shell (bash) executor...
Preparing environment
00:00
Running on l7lp2apmglr0003...
Getting source from Git repository
00:02
Fetching changes with git depth set to 20...
Reinitialized existing Git repository in /home/gitlab-runner/builds/ZNFLWGL4/0/fts-apimanagement/fts-python-microservices/ai-chatbot/.git/
Checking out 2b8ab071 as detached HEAD (ref is main)...
Skipping Git submodules setup
Executing "step_script" stage of the job script
00:17
$ echo "Logging in to Nexus Docker registry..."
Logging in to Nexus Docker registry...
$ echo "$NEXUS_REPO_PASS" | docker login -u "$NEXUS_REPO_USER" --password-stdin $NEXUS_REGISTRY
WARNING! Your password will be stored unencrypted in /home/gitlab-runner/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store
Login Succeeded
$ echo "Building Docker image with Python code..."
Building Docker image with Python code...
$ docker build -t $FULL_IMAGE_NAME .
#0 building with "default" instance using docker driver
#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 923B done
#1 DONE 0.0s
#2 [internal] load metadata for fmk.nexus.onefiserv.net/fmk/python/python-3.9:FMK-01-10-24
#2 DONE 1.1s
#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.1s
#4 [1/6] FROM fmk.nexus.onefiserv.net/fmk/python/python-3.9:FMK-01-10-24@sha256:27e209951b4198d676b6af7b2eef6029bd67ba1682dd91c8037f5ba8dd7c7302
#4 DONE 0.0s
#5 [internal] load build context
#5 transferring context: 215.96kB 0.3s done
#5 DONE 0.3s
#4 [1/6] FROM fmk.nexus.onefiserv.net/fmk/python/python-3.9:FMK-01-10-24@sha256:27e209951b4198d676b6af7b2eef6029bd67ba1682dd91c8037f5ba8dd7c7302
#4 CACHED
#6 [2/6] COPY . /app
#6 DONE 0.8s
#7 [3/6] WORKDIR /app
#7 DONE 0.2s
#8 [4/6] COPY requirements.txt ./
#8 DONE 0.2s
#9 [5/6] ADD requirements.txt /app/
#9 DONE 0.2s
#10 [6/6] RUN python -m pip install -r requirements.txt
#10 2.662 Looking in indexes: https://nexus.onefiserv.net/repository/pypi-proxy/simple
#10 2.673 Collecting fiservai@ https://github.com/tomeck/fsaipkg/releases/download/v0.0.11/fiservai-0.0.11-py3-none-any.whl (from -r requirements.txt (line 2))
#10 2.753   WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))': /tomeck/fsaipkg/releases/download/v0.0.11/fiservai-0.0.11-py3-none-any.whl
#10 3.308   WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))': /tomeck/fsaipkg/releases/download/v0.0.11/fiservai-0.0.11-py3-none-any.whl
#10 4.384   WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))': /tomeck/fsaipkg/releases/download/v0.0.11/fiservai-0.0.11-py3-none-any.whl
#10 6.475   WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))': /tomeck/fsaipkg/releases/download/v0.0.11/fiservai-0.0.11-py3-none-any.whl
#10 10.56   WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))': /tomeck/fsaipkg/releases/download/v0.0.11/fiservai-0.0.11-py3-none-any.whl
#10 10.62 ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /tomeck/fsaipkg/releases/download/v0.0.11/fiservai-0.0.11-py3-none-any.whl (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))
#10 10.62 
#10 11.14 
#10 11.14 [notice] A new release of pip is available: 23.3.1 -> 25.1.1
#10 11.14 [notice] To update, run: pip install --upgrade pip
#10 ERROR: process "/bin/sh -c python -m pip install -r requirements.txt" did not complete successfully: exit code: 1
------
 > [6/6] RUN python -m pip install -r requirements.txt:
2.753   WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))': /tomeck/fsaipkg/releases/download/v0.0.11/fiservai-0.0.11-py3-none-any.whl
3.308   WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))': /tomeck/fsaipkg/releases/download/v0.0.11/fiservai-0.0.11-py3-none-any.whl
4.384   WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))': /tomeck/fsaipkg/releases/download/v0.0.11/fiservai-0.0.11-py3-none-any.whl
6.475   WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))': /tomeck/fsaipkg/releases/download/v0.0.11/fiservai-0.0.11-py3-none-any.whl
10.56   WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))': /tomeck/fsaipkg/releases/download/v0.0.11/fiservai-0.0.11-py3-none-any.whl
10.62 ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /tomeck/fsaipkg/releases/download/v0.0.11/fiservai-0.0.11-py3-none-any.whl (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))
10.62 
11.14 
11.14 [notice] A new release of pip is available: 23.3.1 -> 25.1.1
11.14 [notice] To update, run: pip install --upgrade pip
------
Dockerfile:26
--------------------
  24 |     COPY requirements.txt ./
  25 |     ADD requirements.txt /app/
  26 | >>> RUN python -m pip install -r requirements.txt
  27 |     #python -m pip install --no-cache-dir -r requirements.txt
  28 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c python -m pip install -r requirements.txt" did not complete successfully: exit code: 1
Cleaning up project directory and file based variables
00:00
ERROR: Job failed: exit status 1
