Running with gitlab-runner 16.11.2 (1d04b67a)
  on l7lt2apmglr0004-Global-GitLab-Cloud-Docker-apihub-shared FeEX_mAX, system ID: s_842e1c8182d6
Resolving secrets
Preparing the "docker" executor
00:39
Using Docker executor with image docker:latest ...
Starting service docker:dind ...
Pulling docker image docker:dind ...
Using docker image sha256:6892cb0e669d8bf6d40d1421bfd62b0aec81041706f7b45de7a03514cfef527b for docker:dind with digest docker@sha256:d33eb93fe02683e984e6f8a93c0b3d85bb74f56ec83922bc39fb34ba23ab42bc ...
Waiting for services to be up and running (timeout 30 seconds)...
*** WARNING: Service runner-feexmax-project-48368-concurrent-0-56ef9a9f24874775-docker-0 probably didn't start properly.
Health check error:
service "runner-feexmax-project-48368-concurrent-0-56ef9a9f24874775-docker-0-wait-for-service" timeout
Health check container logs:
2025-06-26T18:23:45.533577578Z waiting for TCP connection to 172.17.0.2 on [2375 2376]...
2025-06-26T18:23:45.533657583Z dialing 172.17.0.2:2376...
2025-06-26T18:23:45.533667784Z dialing 172.17.0.2:2375...
2025-06-26T18:23:46.534421520Z dialing 172.17.0.2:2376...
2025-06-26T18:23:46.534607833Z dialing 172.17.0.2:2375...
Service container logs:
2025-06-26T18:23:45.977995813Z Certificate request self-signature ok
2025-06-26T18:23:45.978075018Z subject=CN=docker:dind server
2025-06-26T18:23:46.003251088Z /certs/server/cert.pem: OK
2025-06-26T18:23:46.069404537Z Certificate request self-signature ok
2025-06-26T18:23:46.069456541Z subject=CN=docker:dind client
2025-06-26T18:23:46.103264817Z /certs/client/cert.pem: OK
2025-06-26T18:23:46.108206764Z cat: can't open '/proc/net/ip_tables_names': No such file or directory
2025-06-26T18:23:46.109741472Z cat: can't open '/proc/net/ip6_tables_names': No such file or directory
2025-06-26T18:23:46.113948268Z cat: can't open '/proc/net/arp_tables_names': No such file or directory
2025-06-26T18:23:46.117791238Z ip: can't find device 'nf_tables'
2025-06-26T18:23:46.119755776Z nf_tables_set          49152 22 
2025-06-26T18:23:46.119782378Z nf_tables             192512 445 nft_counter,nft_compat,nft_fib_inet,nft_fib_ipv4,nft_fib_ipv6,nft_fib,nft_reject_inet,nft_reject,nft_ct,nf_tables_set,nft_chain_nat
2025-06-26T18:23:46.119791979Z nfnetlink              16384  6 nf_conntrack_netlink,nft_compat,ip_set,nf_tables
2025-06-26T18:23:46.119800479Z libcrc32c              16384  4 nf_nat,nf_conntrack,nf_tables,xfs
2025-06-26T18:23:46.121113271Z modprobe: can't change directory to '/lib/modules': No such file or directory
2025-06-26T18:23:46.131127775Z ip: can't find device 'ip_tables'
2025-06-26T18:23:46.136755771Z modprobe: can't change directory to '/lib/modules': No such file or directory
2025-06-26T18:23:46.144708230Z ip: can't find device 'ip6_tables'
2025-06-26T18:23:46.149211146Z modprobe: can't change directory to '/lib/modules': No such file or directory
2025-06-26T18:23:46.159373260Z iptables v1.8.11 (nf_tables)
2025-06-26T18:23:46.165090062Z mount: permission denied (are you root?)
2025-06-26T18:23:46.165132165Z Could not mount /sys/kernel/security.
2025-06-26T18:23:46.165145666Z AppArmor detection and --privileged mode might break.
2025-06-26T18:23:46.174785844Z mount: permission denied (are you root?)
*********
Pulling docker image docker:latest ...
Using docker image sha256:6892cb0e669d8bf6d40d1421bfd62b0aec81041706f7b45de7a03514cfef527b for docker:latest with digest docker@sha256:d33eb93fe02683e984e6f8a93c0b3d85bb74f56ec83922bc39fb34ba23ab42bc ...
Preparing environment
00:01
Running on runner-feexmax-project-48368-concurrent-0 via l7lt2apmglr0004...
Getting source from Git repository
00:02
Fetching changes with git depth set to 20...
Reinitialized existing Git repository in /builds/fts-apimanagement/fts-python-microservices/ai-chatbot/.git/
Checking out 2b8ab071 as detached HEAD (ref is main)...
Skipping Git submodules setup
Executing "step_script" stage of the job script
00:02
Using docker image sha256:6892cb0e669d8bf6d40d1421bfd62b0aec81041706f7b45de7a03514cfef527b for docker:latest with digest docker@sha256:d33eb93fe02683e984e6f8a93c0b3d85bb74f56ec83922bc39fb34ba23ab42bc ...
$ docker login -u "$NEXUS_REPO_USER" -p "$NEXUS_REPO_PASS" $NEXUS_REPO_URL
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
time="2025-06-26T18:24:22Z" level=info msg="Error logging in to endpoint, trying next endpoint" endpoint="{false https://nexus-ci.onefiserv.net false false false 0xc000468000}" error="login attempt to https://nexus-ci.onefiserv.net/v2/ failed with status: 404 Not Found"
login attempt to https://nexus-ci.onefiserv.net/v2/ failed with status: 404 Not Found
Uploading artifacts for failed job
00:01
Uploading artifacts...
WARNING: image.tag: no matching files. Ensure that the artifact path is relative to the working directory (/builds/fts-apimanagement/fts-python-microservices/ai-chatbot) 
ERROR: No files to upload                          
Cleaning up project directory and file based variables
00:00
ERROR: Job failed: exit code 1
